# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FinalProject_CFT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FinalProject_CFT
  pod 'Alamofire', '~> 5.8.1'
  pod 'AlamofireImage', '~> 4.3'
end
